import "~/styles/globals.css";

import { type Metadata } from "next";
import * as fonts from '~/ui/fonts'
import { ClerkProvider } from "@clerk/nextjs";
import { Analytics } from "@vercel/analytics/react"

export const metadata: Metadata = {
	title: "DevLog",
	description: "Generated by create-t3-app",
	icons: [{ rel: "icon", url: "https://utfs.io/f/646deb37-2201-4452-8270-3cdc10add709-hru0oc.ico" }],
};

export default function RootLayout({
	children,
}: Readonly<{ children: React.ReactNode }>) {

	return (
		<ClerkProvider >
			<html lang="en" className={`${fonts.open_sans.className} antialiased overflow-scroll md:overflow-hidden`}>
				<body className="bg-background text-primaryText">
					<div className="flex">
						{children}
					</div>
				</body>
			</html>
		</ClerkProvider>
	);
}
