import "~/styles/globals.css";

import { type Metadata } from "next";
import * as fonts from '~/ui/fonts'

export const metadata: Metadata = {
	title: "DevLog",
	description: "Generated by create-t3-app",
	icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
	children,
}: Readonly<{ children: React.ReactNode }>) {

	return (
		<html lang="en" className={`${fonts.open_sans.className} antialiased overflow-scroll md:overflow-hidden`}>
			<body className="bg-background text-primaryText">
				<div className="flex">
					{children}
				</div>
			</body>
		</html>
	);
}
