import "~/styles/globals.css";

import { type Metadata } from "next";
import * as fonts from '~/ui/fonts'
import { LeftNav, RightNav } from "~/app/_components";

export const metadata: Metadata = {
	title: "DevLog",
	description: "Generated by create-t3-app",
	icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
	children,
}: Readonly<{ children: React.ReactNode }>) {

	return (
		<html lang="en" className={`${fonts.open_sans.className} antialiased overflow-scroll md:overflow-hidden`}>
			<body className="md:grid md:grid-cols-3 bg-background text-primaryText divide-y md:divide-x divide-border flex flex-col md:overflow-hidden min-w-screen">
				<LeftNav />
				<div className="flex">
					{children}
				</div>
				<RightNav />
			</body>
		</html>
	);
}
